/**
 * usersList action type
 * @type { String }
 */
export const API_LOADING = 'API_LOADING'

export const SUCCESS_GET_USERS_LIST = 'SUCCESS_GET_USERS_LIST'
export const FAILED_GET_USERS_LIST = 'FAILED_GET_USERS_LIST'

export const ON_SELECT_USER = 'ON_SELECT_USER'

export const ON_CHANGE_PAGE_NUM = 'ON_CHANGE_PAGE_NUM'

export const SUCCESS_GET_USER_DETAIL = 'SUCCESS_GET_USER_DETAIL'
export const FAILED_GET_USER_DETAIL = 'FAILED_GET_USER_DETAIL'
